"""Add unit_price to RawMaterial

Revision ID: 3bde5190d2bb
Revises: 
Create Date: 2024-09-21 03:19:00.390573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bde5190d2bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
